global_costmap:
  global_frame: map
  robot_base_frame: base_footprint

  update_frequency: 10.0
  publish_frequency: 5.0

  always_send_full_costmap: true

  inflation_radius: 1.05
  cost_scaling_factor: 10

  #width: 30.0
  #height: 30.0
  #origin_x: -15.0
  #origin_y: -15.0

  transform_tolerance: 0.5

  static_map: true
  rolling_window: false